namespace AffiliateProgramManagementSystem.Exceptions;

/// <summary>
/// This is the standard model object for all errors returned by the API if thrown from an exception.
/// </summary>
/// <remarks>
/// This class does not replace the standard .net 7 or fluent validation error messages.
/// </remarks>
public class ApiError
{

    /// <summary>
    /// A trace Id generated by the .net pipeline and logged internally and referenced externally.
    /// </summary>
    public string? TraceId { get; set; }

    /// <summary>
    /// The type of error - this is usually the name of the APIException being thrown
    /// </summary>
    public string? Type { get; set; }

    /// <summary>
    /// The exception message to be returned to the client.  This should be treated as if it was public information.
    /// </summary>
    public string? Message { get; set; }

    /// <summary>
    /// Any custom data object that needs to be returned to the client.  This should be treated as if it was public information.
    /// </summary>
    public dynamic? Data { get; set; }
}
